apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-helm-templates.fullname" . }}
  labels:
    {{- include "k8s-helm-templates.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-helm-templates.selectorLabels" . | nindent 4 }}